name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install frontend dependencies
        run: npm ci --legacy-peer-deps

      # Step 4: Run tests
      - name: Run tests
        run: npm run test:unit

      # Step 5: Lint code
      - name: Lint frontend
        run: npm run lint

      # Step 6: Build frontend
      - name: Build frontend
        run: npm run build

      # Step 7: Deploy to Netlify
      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --dir=dist --auth=$NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}


