name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      # Step 4: Run unit tests with Jest
      - name: Run Jest unit tests
        working-directory: frontend
        run: npm run test:unit

      # Step 5: Lint the frontend code
      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

      # Step 6: Build the frontend
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # Step 7: Simulate deployment
      - name: Simulate deployment
        run: |
          mkdir -p deployment/public
          cp -r frontend/dist/* deployment/public/
          zip -r deployment.zip deployment
        shell: bash

      # Step 8: Upload deployment artifact
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-deployment
          path: deployment.zip


