name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: [build] 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} 
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
        run: netlify deploy --dir=dist --prod

